.\" 
.\" 
.\" Copyright (c) 2011, Stephane Sezer
.\" All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"     * Redistributions of source code must retain the above copyright
.\"       notice, this list of conditions and the following disclaimer.
.\"     * Redistributions in binary form must reproduce the above copyright
.\"       notice, this list of conditions and the following disclaimer in the
.\"       documentation and/or other materials provided with the distribution.
.\"     * Neither the name of Stephane Sezer nor the names of its contributors
.\"       may be used to endorse or promote products derived from this software
.\"       without specific prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL Stephane Sezer BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\" 
.\" 
.TH DPLBCK-RESTORE 1 "2011" "" ""
.SH NAME
dplbck-restore \- restore a backup from a remote storage
.SH SYNOPSIS
.B dplbck restore [
.I options
.B ] <
.I storage
.B > <
.I backup
.B >
.SH DESCRIPTION
.B dplbck restore
restores a previously made backup from a remote storage to the current
directory.
.SH OPTIONS
.TP
.B --profile, -p
Profile to use with the
.I dpl
type storage.
.TP
.B --profile-dir, -d
Directory in which the
.I dpl
profile should be searched.
.TP
.B --verbose, -v
Verbose mode. A line is displayed for each file restored.
.TP
.B --interactive, -i
Interactively ask for the name of the backup to restore if none was
specified on the command line.
.SH RETURN VALUE
.B dplbck restore
returns 0 on success, and non-zero on error.
.SH BUGS
Please send problems, bugs, questions, desirable enhancements, patches
etc. to sas@cd80.net.
.SH AUTHOR
Stephane Sezer <sas@cd80.net>
.SH SEE ALSO
.BR dplbck (1),
.BR dplbck-backup (1),
.BR dplbck-delete (1)
.BR dplbck-list (1)
